document.writeln("<footer class=\'page-footer\'>");
document.writeln("            <div class=\'service-footer-container\' id=\'contactUs\'>");
document.writeln("                <div class=\'service-footer-container2\' data-ga-category=\'Footer\'>");
document.writeln("                    <div class=\'service-footer\' data-ga-label=\'Content Links\'>");
document.writeln("                        <div class=\'service-footer__col\'>");
document.writeln("                            <h4>联系我们</h4>");
document.writeln("                            <div class=\'follow-us\'>");
document.writeln("                                <div class=\'followPrev\'><img src=\'image/common/wx.png\' alt=\'图标\'></div>");
document.writeln("                                <div class=\'followNext\'><img src=\'image/common/code.png\' alt=\'二维码\'></div>");
document.writeln("                                <div class=\'followPrev\'><img src=\'image/common/phone.png\' alt=\'图标\'></div>");
document.writeln("                                <div class=\'followNext\'>联系电话：400-xxx-xxxx</div>");
document.writeln("                                <div class=\'followPrev\'><img src=\'image/common/email.png\' alt=\'图标\'></div>");
document.writeln("                                <div class=\'followNext\'>邮箱地址：lerenkang@lrk.com</div>");
document.writeln("                                <div class=\'followPrev\'><img src=\'image/common/address.png\' alt=\'图标\'></div>");
document.writeln("                                <div class=\'followNext\'>联系地址：北京市朝阳区建国路93号万达广场9号楼九层</div>");
document.writeln("                                <div class=\'followPrev\'><img src=\'image/common/qq.png\' alt=\'图标\'></div>");
document.writeln("                                <div class=\'followNext\'>暂未开放，敬请期待</div>");
document.writeln("                            </div>");
document.writeln("                        </div>");
document.writeln("                    </div>");
document.writeln("                </div>");
document.writeln("            </div>");
document.writeln("            <a href=\'#\' class=\'page-top shadowDepth1 border-tlr-radius track-event\' data-trackname=\'page-top\'>Top</a>");
document.writeln("            <div class=\'content-footer-container\'>");
document.writeln("                <div class=\'content-footer\'>");
document.writeln("                    <ul class=\'legaladvice\' style=\'text-align:center;    font-size: 123%;\'>");
document.writeln("                        <li>");
document.writeln("                            <ul class=\'follow-us follow-us-jz\'>");
document.writeln("                                <li class=\'follow-us__item\' style=\'position: relative;\'>");
document.writeln("                                    <a href=\'index.html#product\' class=\'fl\'>产品与服务</a>");
document.writeln("                                </li>");
document.writeln("                                <li class=\'follow-us__item u-hide-small\' style=\'position: relative;\'>");
document.writeln("                                    |");
document.writeln("                                </li>");
document.writeln("                                <li class=\'follow-us__item\'>");
document.writeln("                                    <a href=\'index.html#knowledge\' class=\'fl\'>健康科技</a>");
document.writeln("                                </li>");
document.writeln("                                <li class=\'follow-us__item u-hide-small\' style=\'position: relative;\'>");
document.writeln("                                    |");
document.writeln("                                </li>");
document.writeln("                                <li class=\'follow-us__item\'>");
document.writeln("                                    <a href=\'index.html#news\' class=\'fl\'>行业动态</a>");
document.writeln("                                </li>");
document.writeln("                                <li class=\'follow-us__item u-hide-small\' style=\'position: relative;\'>");
document.writeln("                                    |");
document.writeln("                                </li>");
document.writeln("                                <li class=\'follow-us__item\'>");
document.writeln("                                    <a href=\'index.html#aboutUs\' class=\'fl\'>关于我们</a>");
document.writeln("                                </li>");
document.writeln("                            </ul>");
document.writeln("                            <br/>Copyright © 北京乐仁康健康咨询有限公司 京ICP备20026845号");
//非经营性-8888888 京公网安备 88888888888888号
document.writeln("                        </li>");
document.writeln("                    </ul>");
document.writeln("                    <div class=\'printfooter\'>");
document.writeln("                        <!-- REPLACE: current URL -->");
document.writeln("                    </div>");
document.writeln("                </div>");
document.writeln("            </div>");
document.writeln("        </footer>");
