document.writeln("<div class=\'pageheader\'>");
document.writeln("                    <header id=\'header\'><a href=\'index.html\' title=\'Homepage\' class=\'logo\'><img src=\'image/common/logo.png\' aria-label=\'Bayer\' alt=\'\' /></a>");
document.writeln("                        <div class=\'site-identifier site-identifier--short\'><a href=\'index.html\' title=\'Homepage\' style=\'font-weight: 400;\'>乐仁康健康</a></div>");
document.writeln("                    </header>");
document.writeln("                    <nav role=\'navigation\' class=\'navigation\'>");
document.writeln("                        <ul id=\'mega-menu-1\' class=\'megamenu\'>");
document.writeln("                            <li class=\'n2\'><a href=\'index.html#aspnetForm\' class=\'haschild\'>首页</a></li>");
document.writeln("                            <li class=\'n3\'><a href=\'index.html#product\' class=\'haschild\'>产品与服务</a></li>");
document.writeln("                            <li class=\'n4\'><a href=\'index.html#knowledge\' class=\'haschild\'>健康科技</a></li>");
document.writeln("                            <li class=\'n5\'><a href=\'index.html#news\' class=\'haschild\'>行业动态</a></li>");
document.writeln("                            <li class=\'n6\'><a class=\'haschild\'>会员中心</a></li>");
document.writeln("                            <li class=\'n7\'><a href=\'index.html#aboutUs\' class=\'haschild\'>关于我们</a></li>");
document.writeln("                            <li class=\'n9\'><a href=\'index.html#contactUs\' class=\'haschild\'>联系我们</a></li>");
document.writeln("                        </ul>");
document.writeln("                    </nav>");
document.writeln("                </div>");
